services:
  chorumebot:
    container_name: chorumebot-app
    image: brunofunnie/chorumebot:latest
    build:
      context: ./docker
      dockerfile: web.dockerfile
    volumes:
      - ./:/app
    networks:
      chorumebot:

  mysql:
    container_name: chorumebot-mysql
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chorumebot
      - MYSQL_USER=chorumebot
      - MYSQL_PASSWORD=chorumebot
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/confs/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
       chorumebot:

  pma:
    container_name: chorumebot-pma
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=2048M
      - UPLOAD_LIMIT=2048M
    networks:
       chorumebot:

  redis:
    container_name: chorumebot-redis
    image: redis:7.2.0-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - redis:/data
    networks:
       chorumebot:

  mpit:
    container_name: chorumebot-mailpit
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ=America/Sao_Paulo
    networks:
       chorumebot:

networks:
  chorumebot:

volumes:
  mysql:
  redis:
