services:
  mysql:
    container_name: dbot-mysql
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chorume_coins
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
    volumes:
      - app_mysql:/var/lib/mysql
      - ./docker/confs/mysql/my.cnf:/etc/mysql/my.cnf

  pma:
    container_name: dbot-pma
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=2048M
      - UPLOAD_LIMIT=2048M

  redis:
    container_name: dbot-redis
    image: redis:7.2.0-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - app_redis:/data

  mpit:
    container_name: dbot-mailpit
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ=America/Sao_Paulo
networks:
  dbot:
    driver: bridge

volumes:
  app_mysql:
  app_redis:
